### ISSUE TITLE
New lasgun is _loud_

### ISSUE THREAD

**Issue by necessarily-equal** [UnvanquishedAssets/res-weapons_src.dpkdir#6]
I've tried playing a match as an alien against bots on 0.52 and one of the things I noticed on early stages is the lasgun sound. I get the impression one can hear it from the other side of the map. I've turned around several time because I though some human with a lasgun sneaked right behind me only to see nothing and be surprised not to see my health bar going down. The weapon is louder than the Mass Rifle!

We probably need to adjust the volume of the audio so that it is reasonable, and maybe also check that the volume indeed decreases as much as it should with distance (but maybe it's just that it was too loud in the first place).

Nice job on the weapon btw, it feels really powerful!

CC @hypov8

**Comment by illwieckz** [comment]
The issue was not the loudness of the soundfile, but that the file was kept stereo and positional audio must be mono (and our engine does not play stereo files as positional ones), so instead of playing the sound effects from other player position, it was playing _right in your head_, even if the player is far and unseen, as soon as it's in the same area of the map. For example a human player at plat23 human base entrance would have heard another human player firing a lasgun at alien base entrance with full loudness…

Note: no need to ping hypov8 for this, the author of the sound effect (and the model) was chris, what did hypov8 was to convert the first person model from chris into a third person model. So, hypov8 is not really concerned by this.
